import type { Lead } from "@/types/lead";
import { buildDiagnosis, computeLeadScore, recommendedActionFor, temperatureFromScore } from "@/lib/scoring";

const now = "2026-06-03T10:00:00.000Z";

const rawSeeds: Array<Omit<Lead, "score" | "temperature" | "diagnosis" | "recommendedAction" | "createdAt" | "updatedAt">> = [
  {
    id: "demo-restaurant-castalla",
    name: "Demo Restaurante Centro",
    sector: "Restaurante",
    city: "Castalla",
    address: "Castalla",
    phone: "",
    website: "",
    googleMapsUrl: "",
    rating: 4.4,
    reviews: 180,
    photos: 4,
    channels: { google: "ok", whatsapp: "weak", instagram: "weak", facebook: "none", website: "none" },
    status: "Prioritario",
    monthlyPotential: 690,
    pain: "Días flojos entre semana y poca reserva directa.",
    nextAction: "Visita presencial antes del servicio de cenas",
    nextActionDate: "2026-06-07",
    notes: "Demo. Sustituir por comercio real importado desde Google Places.",
    lastContact: "",
    lastChecked: "2026-06-03",
    source: "demo"
  },
  {
    id: "demo-clinic-ibi",
    name: "Demo Clínica Salud",
    sector: "Clínica",
    city: "Ibi",
    address: "Ibi",
    phone: "",
    website: "https://example.com",
    googleMapsUrl: "",
    rating: 4.7,
    reviews: 95,
    photos: 2,
    channels: { google: "ok", whatsapp: "none", instagram: "weak", facebook: "weak", website: "ok" },
    status: "Validado",
    monthlyPotential: 790,
    pain: "Necesita más confianza antes de pedir cita.",
    nextAction: "Preparar mini diagnóstico visual",
    nextActionDate: "2026-06-10",
    notes: "Demo.",
    lastContact: "",
    lastChecked: "2026-06-03",
    source: "demo"
  },
  {
    id: "demo-gym-onil",
    name: "Demo Gym Training",
    sector: "Gimnasio",
    city: "Onil",
    address: "Onil",
    phone: "",
    website: "",
    googleMapsUrl: "",
    rating: 4.2,
    reviews: 62,
    photos: 3,
    channels: { google: "weak", whatsapp: "weak", instagram: "ok", facebook: "weak", website: "none" },
    status: "Detectado",
    monthlyPotential: 590,
    pain: "Tiene movimiento, pero no un sistema claro de prueba/alta.",
    nextAction: "Buscar Instagram y validar actividad",
    nextActionDate: "2026-06-11",
    notes: "Demo.",
    lastContact: "",
    lastChecked: "2026-06-03",
    source: "demo"
  },
  {
    id: "demo-estetica-petrer",
    name: "Demo Centro Estética",
    sector: "Estética",
    city: "Petrer",
    address: "Petrer",
    phone: "",
    website: "",
    googleMapsUrl: "",
    rating: 4.8,
    reviews: 42,
    photos: 1,
    channels: { google: "weak", whatsapp: "none", instagram: "ok", facebook: "none", website: "none" },
    status: "Visita pendiente",
    monthlyPotential: 490,
    pain: "Imagen mejorable y reservas poco ordenadas.",
    nextAction: "Visitar al cierre de mañana",
    nextActionDate: "2026-06-12",
    notes: "Demo.",
    lastContact: "",
    lastChecked: "2026-06-03",
    source: "demo"
  },
  {
    id: "demo-taller-sax",
    name: "Demo Taller Motor",
    sector: "Taller",
    city: "Sax",
    address: "Sax",
    phone: "",
    website: "",
    googleMapsUrl: "",
    rating: 4.1,
    reviews: 125,
    photos: 0,
    channels: { google: "weak", whatsapp: "weak", instagram: "none", facebook: "weak", website: "none" },
    status: "Detectado",
    monthlyPotential: 390,
    pain: "Mucho cliente potencial busca por Google, pero la imagen no ayuda.",
    nextAction: "Validar teléfono y horario",
    nextActionDate: "2026-06-13",
    notes: "Demo.",
    lastContact: "",
    lastChecked: "2026-06-03",
    source: "demo"
  },
  {
    id: "demo-comercio-villena",
    name: "Demo Comercio Local",
    sector: "Comercio",
    city: "Villena",
    address: "Villena",
    phone: "",
    website: "https://example.com",
    googleMapsUrl: "",
    rating: 4.6,
    reviews: 35,
    photos: 5,
    channels: { google: "ok", whatsapp: "ok", instagram: "weak", facebook: "weak", website: "ok" },
    status: "Interesado",
    monthlyPotential: 450,
    pain: "Quiere más movimiento desde redes y Google.",
    nextAction: "Mandar propuesta sencilla",
    nextActionDate: "2026-06-09",
    notes: "Demo.",
    lastContact: "2026-06-02",
    lastChecked: "2026-06-03",
    source: "demo"
  }
];

export const seedLeads: Lead[] = rawSeeds.map((lead) => {
  const score = computeLeadScore(lead);
  return {
    ...lead,
    score,
    temperature: temperatureFromScore(score),
    diagnosis: buildDiagnosis(lead),
    recommendedAction: recommendedActionFor(lead),
    createdAt: now,
    updatedAt: now
  };
});
